name: 'AZNFS Prep Machine'
description: 'Prepare the machine for AZNFS'

inputs:
  RUNS_ON:
    description: 'The runs-on value of the self-hosted runner.'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Setup self hosted runner
      shell: bash
      run: |
        chmod +x $GITHUB_WORKSPACE/.github/actions/aznfs-prep-machine/machineSetup.sh
        $GITHUB_WORKSPACE/.github/actions/aznfs-prep-machine/machineSetup.sh "${{ inputs.RUNS_ON }}"

