#!/bin/bash

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

if [ "$1" == 'remove' -o "$1" == 'purge' ]; then
    chattr -f -i /opt/microsoft/aznfs/data/mountmap
    chattr -f -i /opt/microsoft/aznfs/data/randbytes
    rm -rf /opt/microsoft/aznfs
elif [ "$1" == 'upgrade' ]; then
    chattr -f +i /opt/microsoft/aznfs/config.txt
fi