#!/bin/bash

# Exit on error.
set -e

echo "===== postrm called. ====="

chattr -i /opt/microsoft/aznfs/mountmap
rm -r /opt/microsoft/aznfs
echo "Cleaned /opt/microsoft/aznfs directory."

echo "===== postrm called. ====="