#!/bin/bash

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

# Exit on error.
set -e
RED="\e[2;31m"
NORMAL="\e[0m"

if [ "$1" == 'remove' -o "$1" == 'purge' ]; then
	# Verify if any existing mounts are there, warn the user about this.
	existing_mounts=$(cat /opt/microsoft/aznfs/data/mountmap 2>/dev/null | egrep '^\S+' | wc -l)
	if [ $existing_mounts -ne 0 ]; then
		echo
		echo -e "${RED}There are existing Azure Blob NFS mounts using aznfs mount helper, they will not be tracked!"
		echo -n -e "Are you sure you want to continue? [y/N]${NORMAL} "
		read -n 1 result
		echo
		if [ "$result" != "y" -a "$result" != "Y" ]; then
			echo "Removal aborted!"
			exit 1
		fi
	fi
fi

flag_file="/tmp/.update_in_progress_from_watchdog.flag"

if [ -f "$flag_file" ]; then
	# Get the PID of aznfswatchdog
	aznfswatchdog_pid=$(pgrep aznfswatchdog)
	
	# Read the PID from the flag file
	aznfswatchdog_pid_inside_flag=$(cat $flag_file)
	echo "aznfswatchdog_pid_inside_flag: $aznfswatchdog_pid_inside_flag" # remove later
	
	if [ "$aznfswatchdog_pid" != "$aznfswatchdog_pid_inside_flag" ]; then
		# The flag file is stale, remove it
		rm -f "$flag_file"
		echo "Removed stale flag file."
	fi
fi

if [ ! -f "$flag_file" ]; then
	# Stop aznfswatchdog service and clean it.
	systemctl stop aznfswatchdog
	systemctl disable aznfswatchdog
	echo "Stopped aznfswatchdog service."
fi