#! /bin/bash

APPNAME="azblobnfs"

logfile="/run/azblobnfs/${APPNAME}.log" 

RED="\e[2;31m"
RED_BOLD="\e[1;31m"
GREEN="\e[2;32m"
GREEN_BOLD="\e[1;32m"
YELLOW="\e[2;33m"
YELLOW_BOLD="\e[1;33m"
NORMAL="\e[0m"
NORMAL_BOLD="\e[0;1m"

_log()
{
    echoarg=""

    # We only support -n argument to echo.
    if [ "$1" == "-n" ]; then
        echoarg="-n"
        shift
    fi

    color=$1
    msg=$2

    echo $echoarg -e "${color}${msg}${NORMAL}" |& tee -a $logfile
    logger -t $APPNAME -- "$msg"
}

#
# plain echo with file logging.
#
pecho()
{
    echoarg=""
    color=$NORMAL
    if [ "$1" == "-n" ]; then
        echoarg="-n"
        shift
    fi
    _log $echoarg $color "${*}"
}

# success echo.
secho()
{
    echoarg=""
    color=$GREEN
    if [ "$1" == "-n" ]; then
        echoarg="-n"
        shift
    fi
    _log $echoarg $color "${*}"
}

# warning echo.
wecho()
{
    echoarg=""
    color=$YELLOW
    if [ "$1" == "-n" ]; then
        echoarg="-n"
        shift
    fi
    _log $echoarg $color "${*}"
}

# error echo.
eecho()
{
    echoarg=""
    color=$RED
    if [ "$1" == "-n" ]; then
        echoarg="-n"
        shift
    fi
    _log $echoarg $color "${*}"
}