#!/bin/bash

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

# Exit on error.
set -e

FLAG_FILE="/tmp/.update_in_progress_from_watchdog.flag"
CONFIG_FILE="/opt/microsoft/azfiles-nfs/data/config"
AUTO_UPDATE_AZFILES_NFS="false"

is_aznfs_installed()
{
    dpkg-query -W -f='${Status}' aznfs 2>/dev/null | grep -Eq "install ok (installed|unpacked|half-configured|half-installed|triggers-awaited|triggers-pending)"
}

parse_user_config()
{
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "[BUG] $CONFIG_FILE not found, proceeding with default values..."
        return
    fi

    # Read the value of AUTO_UPDATE_AZFILES_NFS from the configuration file and convert to lowercase for easy comparison later.
    AUTO_UPDATE_AZFILES_NFS=$(egrep -o '^AUTO_UPDATE_AZFILES_NFS[[:space:]]*=[[:space:]]*[^[:space:]]*' "$CONFIG_FILE" | tr -d '[:blank:]' | cut -d '=' -f2)
    AUTO_UPDATE_AZFILES_NFS=${AUTO_UPDATE_AZFILES_NFS,,}
}

user_consent_for_auto_update()
{
    if is_aznfs_installed; then
        # When aznfs is installed, azfiles-nfs is updated through aznfs dependency.
        sed -i '/AUTO_UPDATE_AZFILES_NFS/d' "$CONFIG_FILE"
        echo "AUTO_UPDATE_AZFILES_NFS=false" >> "$CONFIG_FILE"
        return
    fi

    parse_user_config

    if [ "$AUTO_UPDATE_AZFILES_NFS" == "true" ]; then
        return
    fi

    sed -i '/AUTO_UPDATE_AZFILES_NFS/d' "$CONFIG_FILE"

    if [ "$DEBIAN_FRONTEND" == "noninteractive" ] || [ "$AZNFS_NONINTERACTIVE_INSTALL" == "1" ]; then
        echo "AUTO_UPDATE_AZFILES_NFS=true" >> "$CONFIG_FILE"
        return
    fi

    title="Enable auto update for AZFILES_NFS mount helper"
    auto_update_prompt=$(cat << EOF
    Stay up-to-date with the latest features, improvements, and security patches!

    AUTO-UPDATE WILL JUST UPDATE THE MOUNT HELPER BINARY AND WILL NOT CAUSE ANY DISRUPTION TO MOUNTED SHARES.

    We recommend enabling automatic updates for the best/seamless AZFILES_NFS experience.

    You can turn off auto-update at any time from /opt/microsoft/azfiles-nfs/data/config.
EOF
)

    if whiptail --title "$title" --yesno "$auto_update_prompt" 0 0; then
        echo "AUTO_UPDATE_AZFILES_NFS=true" >> "$CONFIG_FILE"
    else
        echo "AUTO_UPDATE_AZFILES_NFS=false" >> "$CONFIG_FILE"
    fi
}

# Set appropriate permissions.
chmod 0755 /opt/microsoft/azfiles-nfs/
chmod 0755 /usr/sbin/aznfswatchdogv4
chmod 0755 /opt/microsoft/azfiles-nfs/mountscript.sh
chmod 0755 /opt/microsoft/azfiles-nfs/nfsv4mountscript.sh
chmod 0755 /opt/microsoft/azfiles-nfs/aznfs_install.sh
chmod 0755 /opt/microsoft/azfiles-nfs/azfiles_install.sh
chmod 0644 /opt/microsoft/azfiles-nfs/common.sh
chmod 0644 /lib/systemd/system/aznfswatchdogv4.service

# Set suid bit for mount.aznfs to allow mount for non-super user.
chmod 4755 /sbin/mount.aznfs

# Create data directory for holding mountmap and log file. 
mkdir -p /opt/microsoft/azfiles-nfs/data
chmod 0755 /opt/microsoft/azfiles-nfs/data

# Create log directory under /etc/stunnel to store stunnel logs
mkdir -p /etc/stunnel/microsoft/azfiles-nfs/nfsv4_fileShare/logs
chmod 0644 /etc/stunnel/microsoft/azfiles-nfs/nfsv4_fileShare/logs

if [ -f /opt/microsoft/azfiles-nfs/azfiles-nfs.log ]; then
        mv -vf /opt/microsoft/azfiles-nfs/azfiles-nfs.log /opt/microsoft/azfiles-nfs/data/
fi

if [ -f /opt/microsoft/azfiles-nfs/randbytes ]; then
        chattr -f -i /opt/microsoft/azfiles-nfs/randbytes
        mv -vf /opt/microsoft/azfiles-nfs/randbytes /opt/microsoft/azfiles-nfs/data/
        chattr -f +i /opt/microsoft/azfiles-nfs/data/randbytes
fi

# Check if the config file exists; if not, create it.
if [ ! -f "$CONFIG_FILE" ]; then
        # Create the config file and set default AUTO_UPDATE_AZFILES_NFS=false inside it.
        echo "AUTO_UPDATE_AZFILES_NFS=false" > "$CONFIG_FILE"

        # Set the permissions for the config file.
        chmod 0644 "$CONFIG_FILE"
fi

#
# If it's an auto update triggered by aznfswatchdogv4, don't restart watchdog.
# Additionally, ask user about auto update configuration.
#
if [ ! -f "$FLAG_FILE" ]; then
        user_consent_for_auto_update

        # Wanted by watchdog service
        systemctl enable nfs-client.target

        systemctl daemon-reload
        # Start the watchdog service for NFSv4
        systemctl enable aznfswatchdogv4
        systemctl start aznfswatchdogv4
else
        # Clean up the update in progress flag file.
        rm -f "$FLAG_FILE"
fi
