#!/bin/bash

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

# Exit on error.
set -e
RED="\e[2;31m"
NORMAL="\e[0m"

if [ "$1" == 'remove' -o "$1" == 'purge' ]; then
	# Verify if any v4.1 existing mounts are there, warn the user about this.
	existing_mounts_v4=$(cat /opt/microsoft/azfiles-nfs/data/mountmapv4 2>/dev/null | egrep '^\S+' | wc -l)
	if [ $existing_mounts_v4 -ne 0 ]; then
		echo
		echo -e "${RED}There are existing Azure Files NFS mounts using azfiles-nfs mount helper, they will not be tracked!"
		echo -n -e "Are you sure you want to continue? [y/N]${NORMAL} "
		read -n 1 result
		echo
		if [ "$result" != "y" -a "$result" != "Y" ]; then
			echo "Removal aborted!"
			exit 1
		fi
	fi
fi

flag_file="/tmp/.update_in_progress_from_watchdog.flag"

if [ -f "$flag_file" ]; then
	# Get the PID of aznfswatchdogv4.
	pid_aznfswatchdogv4=$(pgrep -x aznfswatchdogv4)
	
	# Read the PID from the flag file.
	pid_aznfswatchdogv4_in_flagfile=$(cat $flag_file)
	
	if [ "$pid_aznfswatchdogv4" != "$pid_aznfswatchdogv4_in_flagfile" ]; then
		# The flag file is stale, remove it.
		rm -f "$flag_file"
		echo "Removed stale flag file"
	fi
fi

if [ ! -f "$flag_file" ]; then
	# Stop aznfswatchdogv4 service and clean it.
	systemctl stop aznfswatchdogv4
	systemctl disable aznfswatchdogv4

	echo "Stopped aznfswatchdogv4 service"
fi
