name: Example Workflow

on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest

    env:
      MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          # Access the secret using the environment variable
          echo "Secret Token: $MY_SECRET_TOKEN"

          # Pass the secret to your script
          chmod +x $GITHUB_WORKSPACE/your_script.sh
          $GITHUB_WORKSPACE/your_script.sh "$MY_SECRET_TOKEN"
