name: ShellCheck
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
         SHELLCHECK_OPTS: -e SC2034
      with:
        severity: warning
        check_together: 'yes'
        disable_matcher: false
        ignore_paths: vendor release-tools hack
        format: gcc
